### ISSUE TITLE
Request: CMRR .log files

### ISSUE THREAD

**Issue by alexsayal** [cbinyu/bidsphysio#3]
Hello all,

I would like to use this package to convert physio files exported from CMRR multi-Band sequences to the BIDS format. However, when the data were acquired, the physio files were exported as .log files (*_ECG.log, *_RESP.log, *_PULS.log, *_Info.log).

Would it be possible to have these files as input for physio2bidsphysio?

Thank you in advance for your help,

**Comment by pvelasco** [comment]
Hi Alexandre,

Yes, you can use:

```
physio2bidsphysio --infile <myECGfile>.log <myRESPfile>.log <myPULSfile>.log   \
                  --bidsprefix BIDSfolder/sub-01/func/sub-01_task-REST_run-1
```
using the actual filenames for your physiological files and replacing `BIDSfolder/sub-01/func/sub-01_task-REST_run-1` with the BIDS filename you want your physiological files to have.

Please let me know if you encounter any problems.

**Comment by alexsayal** [comment]
Hello @pvelasco ,

I tried that, but I get this error:

`Traceback (most recent call last):
  File "/home/alexandresayal/miniconda3/envs/bids_env/bin/physio2bidsphysio", line 8, in <module>
    sys.exit(main())
  File "/home/alexandresayal/miniconda3/envs/bids_env/lib/python3.9/site-packages/bidsphysio/physio2bids/physio2bidsphysio.py", line 83, in main
    raise Exception("{fe} is not a known physio file extension.".format(fe=fileExtension))
Exception: log is not a known physio file extension.
`

**Comment by pvelasco** [comment]
I committed a quick patch. Do you mind trying it (I don't have any `.log` files)?
You could just `git pull` the code, `cd ` to the bidsphysio directory and do a `pip install .`
Otherwise, could you send me one of the `.log` files (without any subject identifiable info) to pablo dot velasco at nyu dot edu?
Thanks.

**Comment by alexsayal** [comment]
Just sent you the .log files via email.

**Comment by pvelasco** [comment]
Hi @alexsayal ,

Thank you for sending the files; they were of great help.

I have committed the necessary changes for `physio2bidsphysio` to handle the CMRR `.log` files.

Please install the new version and try again (using the call above).

**Comment by alexsayal** [comment]
Hello @pvelasco ,

Thank you for the update! I am now able to read the .log files.

However, I think the sampling rates for both signals are incorrect. The cardiac signal is recorded in these files at 200 Hz (SampleTime=2, tics=2.5 ms, fs=1/(0.0025*2)=200 ) and the respiratory at 50 Hz (SampleTime=8).

This might explain the mismatch between the cardiac/respiratory and the trigger columns when comparing with the original files.

Do you agree?

**Comment by pvelasco** [comment]
Thanks for pointing this out, @alexsayal !
I thought that `SampleTime` was in units of ms, not in the "2.5 ms" units.
So I assume the TR for this sequence was 1 second, right?

I will modify the code and let you know when it is ready for you to test.

**Comment by pvelasco** [comment]
Hi @alexsayal ,
I have committed a new branch ([fix_dcm_sampletime](/cbinyu/bidsphysio/tree/fix_dcm_sampletime)) that fixes the timing.
Do you mind checking that it works for you?
Thank you!

**Comment by alexsayal** [comment]
Hello @pvelasco ,

I had some difficulty installing the new version (the pip command kept installing version 1.3.1 of physio2bids, instead of 1.3.2). I had to do `pip install ./bidsphysio.physio2bidsphysio`. But now it is working! I validate the new sampling rates and the match between the Info and PULS and RESP files.

Thank you for the update!

**Comment by pvelasco** [comment]
Thanks for the update.
I will now merge the new branch into the master branch and upload the new version to PyPI, so that it can be installed via `pip install bidsphysio`
